services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1024m -Xmx4056m"
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: true
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  #  logstash:
  #    image: logstash:8.11.0
  #    container_name: log
  #    environment:
  #      discovery.seed_hosts: logstash
  #      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
  #    volumes:
  #      - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
  #      - ./logstash/nginx.log:/home/nginx.log
  #    ports:
  #      - "5000:5000/tcp"
  #      - "5000:5000/udp"
  #      - "5044:5044"
  #      - "9600:9600"
  #    depends_on:
  #      - elasticsearch
  #    networks:
  #      - elastic
  #    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
